FROM n8nio/n8n:latest

# Extend here for system packages or global modules used by Execute Command / Code nodes.
USER root
RUN npm install -g tsx cheerio@1.2.0 \
    && ln -s /usr/local/lib/node_modules/cheerio /usr/local/lib/node_modules/n8n/node_modules/cheerio
USER node
